/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SQL;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author JA Rodriguez
 */
public class ProyectoPP extends javax.swing.JFrame {

    /**
     * Creates new form ProyectoPP
     */
    public ProyectoPP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConectar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuA = new javax.swing.JMenu();
        irA = new javax.swing.JMenuItem();
        menuB = new javax.swing.JMenu();
        irB = new javax.swing.JMenuItem();
        menuC = new javax.swing.JMenu();
        menuD = new javax.swing.JMenu();
        menuE = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        menuA.setText("A");
        menuA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAActionPerformed(evt);
            }
        });

        irA.setText("ir A");
        irA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irAActionPerformed(evt);
            }
        });
        menuA.add(irA);

        jMenuBar1.add(menuA);

        menuB.setText("B");

        irB.setText("ir B");
        irB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irBActionPerformed(evt);
            }
        });
        menuB.add(irB);

        jMenuBar1.add(menuB);

        menuC.setText("C");
        jMenuBar1.add(menuC);

        menuD.setText("D");
        jMenuBar1.add(menuD);

        menuE.setText("E");
        jMenuBar1.add(menuE);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(btnConectar)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnConectar)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:
        String bases = "";
        try{
           
            Statement sql = Conexion.getConexion().createStatement();
            String consulta = "SELECT top 2 TerritoryID FROM AdventureWorks2019_1.Sales.SalesOrderHeader";
            ResultSet resultado = sql.executeQuery(consulta);
            System.out.println("Hasta esta linea");
            while(resultado.next()){
                bases += resultado.getString(1)+ "\n";
                
            }
            JOptionPane.showMessageDialog(null,  bases);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnConectarActionPerformed

    private void menuAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuAActionPerformed

    private void irAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irAActionPerformed
        // TODO add your handling code here:
        A a = new A();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_irAActionPerformed

    private void irBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irBActionPerformed
        // TODO add your handling code here:
        B b = new B();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_irBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoPP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JMenuItem irA;
    private javax.swing.JMenuItem irB;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuA;
    private javax.swing.JMenu menuB;
    private javax.swing.JMenu menuC;
    private javax.swing.JMenu menuD;
    private javax.swing.JMenu menuE;
    // End of variables declaration//GEN-END:variables
}
